import MetaTrader5 as mt5

# ==========================================
# ⚙️ GLOBAL CONFIGURATION
# ==========================================
SYMBOL = "XAUUSD"
TIMEFRAME_TREND = mt5.TIMEFRAME_H1
TIMEFRAME_ENTRY = mt5.TIMEFRAME_M5
TIMEFRAME_ADX   = mt5.TIMEFRAME_M15  

# 🛡️ 1. VOLATILITY GUARD 
USE_VOLATILITY_GUARD = True
ATR_BASELINE_PERIOD = 100    
VOLATILITY_THRESHOLD = 3.0   

# 🧠 2. DUAL AI SETTINGS
USE_AI_FILTER = True
TREND_MODEL_FILE = "gold_trend_model.joblib"
REVERSAL_MODEL_FILE = "gold_reversal_model.joblib"
AI_CONFIDENCE_THRESHOLD = 0.55

# 🛡️ 3. DYNAMIC RISK (SESSION BASED)
SESSION_RISK = {
    "ASIAN": 0.5,             
    "LONDON": 1.0,            
    "NY_LONDON_OVERLAP": 0.0, # 🛑 FORCED FLAT
    "NEW_YORK": 1.0,          
    "ROLLOVER": 0.0           
}

# 📉 4. AUTO-STRATEGY (ORCHESTRATOR RULES)
AUTO_SWITCH = True       
ADX_TREND_START = 30     
ADX_RANGE_START = 20     

# 🏃 5. MANAGEMENT SETTINGS
USE_ATR_SL = True
SL_ATR_MULTIPLIER = 1.0   
USE_TRAILING_STOP = True
TRAIL_START_DOLLARS = 4.50  
TRAIL_DIST_DOLLARS = 4.00   
USE_TRAILING_TP = True      
TP_TRIGGER_DIST = 1.00      
TP_EXTENSION_DIST = 5.00    
MAX_DAILY_LOSS_PERCENT = 3.0    

# 🧪 6. OPERATION MODES
DRY_RUN = False
CLOSE_ALL_ON_FRIDAY = True
FRIDAY_CLOSE_HOUR = 21
DATA_COLLECT_MODE = True
NEWS_KILL_SWITCH = True
DYNAMIC_RISK = True
MOVE_BE = True
BE_TRIGGER_PCT = 0.5
PARTIAL_CLOSE_PCT = 0.5

# 🌍 7. TIMEZONE & DST SETTINGS
AUTO_DST_ADJUST = True
DST_SHIFT_HOURS = 1      

# STANDARD SETTINGS
MAGIC_NUMBER = 999001
DEVIATION = 20
MIN_GAP_SIZE = 0.10
RISK_REWARD_RATIO = 2.0  
MAX_SPREAD_POINTS = 50   
ASIAN_OPEN_HOUR = 1      
TRADING_END_HOUR = 21    

# INDICATOR PARAMS
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
ADX_PERIOD = 14
